runtime: python
env: flex

runtime_config:
  python_version: 3.7

entrypoint: gunicorn -b :$PORT -k flask_sockets.worker crypto_recommendations_api.main:app

manual_scaling:
  instances: 1

network:
  session_affinity: true
